---
- name: setup pre-requisites
  hosts: all
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file


- name: setup docker user on the nodes
  become: yes
  become_user: docker
  hosts: admin
  roles:
    - configure-admin

- name: copy public key to nodes
  become: yes
  become_user: docker
  hosts: docker_nodes
  roles:
    - copy-keys

- name: install docker
  hosts: docker_nodes
  roles:
    - docker-installation

- name: initialize docker swarm
  hosts: swarm_managers
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  hosts: swarm_workers
  roles:
    - docker-swarm-add-worker

- name: add managers to the swarm
  hosts: swarm_managers
  roles:
    - docker-swarm-add-manager
